config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index'
  resources :posts
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  #GET /posts/:id
  def show
    @post = Post.find(params[:id])
  end

  #GET /post
  def index
    @posts = Post.all
  end

  private
    def post_params
      params.require(:post).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gulp_asset_path(path)
    path = REV_MANIFEST[path] if defined?(REV_MANIFEST)
    "/assets/#{path}"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>全ての投稿一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

  <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
      </tr>
  <% end %>
</table>

<%= link_to '新しい投稿', new_post_path %>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>
<%= form_for :post, url: posts_path do |f| %>
    <p>
      <%= f.label :title, "タイトル" %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text, "内容" %><br>
      <%= f.text_area :text, cols: 60, rows: 8 %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_top '戻る', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>タイトル</strong>
  <%= @post.title %>
</p>
<p>
  <strong>内容:</strong>
  <%= @post.text %>
</p>

<%= link_to '戻る', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to "私のブログ", controller: "posts" %>